### ISSUE TITLE
Add Dielectric Fill to HFSS3DLayout

### ISSUE THREAD

**Issue by fwlfHS** [ansys/pyaedt#3054]
### Description of the feature

Add property dielectric fill material to method `add_layer` in HFSS3DLayout.

### Steps for implementing the feature

in pyaedt/modules/LayerStackup.py adjust:
`add_layer( self, layername, layertype="signal", thickness="0mm", elevation="0mm", material="copper", isnegative=False, fill_material="FR4_epoxy"):`

**Comment by Samuelopez-ansys** [comment]
Hi @fwlfHS ,

This will be considered, but I think current implementation is enough because you add and assign the fill material after you create the layer.


s1 = aedtapp.modeler.layers.add_layer(
            layername="Bottom", layertype="signal", thickness="0.035mm", elevation="0mm", material="iron"
        )

s1.fill_material = "glass"

As you know, if the layers are not signal type, the fill will not be applied, and then this argument will not be used. For that reason, we prefer the current approach.

If you do dir(s1) you will see all properties you could modify.
