### ISSUE TITLE
EDB primitive subtraction operation sometimes creates invalid polygon (overlapping holes)

### ISSUE THREAD

**Issue by xelasch** [ansys/pyaedt#3173]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Suppose you have a polygon X with two holes XH1 and XH2.
Further, suppose you have a polygon Y which is fully contained in the outer perimeter of X, and further assume Y intersects both XH1 and XH2 but is not fully contained in XH1 and XH2 (vice versa).

Then, X.subtract(Y) results in a corrupted polygon, which has three overlapping holes. To my understanding, holes should never overlap. Otherwise, e.g., the computed area is incorrect, and other subsequent boolean operations may fail. That is, because the assumption behind the boolean operatins is that holes don't overlap.

### Steps To Reproduce

import pyaedt
from pyaedt import Edb, Hfss3dLayout

edb = Edb("_foo.edb")

edb.stackup.add_layer(layer_name="foo")

x = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0] ])
x_hole1 = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [1.0, 1.0], [4.5, 1.0], [4.5, 9.0], [1.0, 9.0] ])
## x_hole2 = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [4.5, 1.0], [9.0, 1.0], [9.0, 9.0], [4.5, 9.0] ])
x_hole2 = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [5.5, 1.0], [9.0, 1.0], [9.0, 9.0], [5.5, 9.0] ])
x = x.subtract(x_hole1)[0]
x = x.subtract(x_hole2)[0]

y = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [4.0, 3.0], [6.0, 3.0], [6.0, 6.0], [4.0, 6.0] ])

z = x.subtract(y)[0]

edb.save_edb()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

pyaedt==0.6.78

**Comment by svandenb-dev** [comment]
Hi @xelasch,
I made a test with this code

from pyaedt import Edb, Hfss3dLayout


edb_file = r"C:\Temp\test_subtract\test.aedb"
edb = Edb(edbpath=edb_file)
edb.stackup.add_layer(layer_name="test")
x = edb.modeler.create_polygon(layer_name="test", main_shape=[[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0]])
x_hole1 = edb.modeler.create_polygon(layer_name="test", main_shape=[[1.0, 1.0], [4.5, 1.0], [4.5, 9.0], [1.0, 9.0]])
x_hole2 = edb.modeler.create_polygon(layer_name="test", main_shape=[[4.5, 1.0], [9.0, 1.0], [9.0, 9.0], [4.5, 9.0]])
x = x.subtract([x_hole1, x_hole2])[0]
y = edb.modeler.create_polygon(layer_name="foo", main_shape=[ [4.0, 3.0], [6.0, 3.0], [6.0, 6.0], [4.0, 6.0] ])
z = x.subtract(y)
edb.save_edb()
edb.close_edb()

this gives this, this looks good to me. you can see the inner void but should not cause any solver issues. 
![image](https://github.com/ansys/pyaedt/assets/74993647/254c73e6-5fe8-4f3b-a9f3-b3bfb8f9c9ee).

A good test was to export after to HFSS since this shows what is "seen" by the mesh and the solver
![image](https://github.com/ansys/pyaedt/assets/74993647/b174be5a-9683-4aa3-b190-2dcd714c29f1)
