### ISSUE TITLE
Add "Heal" function to the modeler for access via Q3D to the API

### ISSUE THREAD

**Issue by jefebalconete** [ansys/pyaedt#3367]
### Description of the feature

Sometimes model healing is needed for an analysis to be able to be completed. The options are available in the GUI and work but I haven't been able to access them via API for the modeler in Q3D. 

I only noticed that a colinear_healing method is available for HFSS 3D Layout.

**Comment by gmalinve** [comment]
Hi @jefebalconete,

We have the heal option but at the moment is only available for Maxwell2D and Maxwell3D (as well as the simplify option).
I need to refactor that method in order to make it available for different design types.
This fix will be most probably available in the next release.

Thanks for letting us now,

Regards,

Giulia
