### ISSUE TITLE
Create new example for CS

### ISSUE THREAD

**Issue by gmalinve** [ansys/pyaedt#3586]
Create a new example that encloses all types of coordinate systems that are now available in pyaedt:
- Relative
- Face
- Object

**Comment by gmalinve** [comment]
@DaveTwyman I'll assign this one to myself because I can reuse an already existing example that I was already working on if you agree. PR is already linked.

**Comment by DaveTwyman** [comment]
> @DaveTwyman I'll assign this one to myself because I can reuse an already existing example that I was already working on if you agree. PR is already linked.

Sure go for it,
I did notice there is already a comprehensive CS example here:- https://aedt.docs.pyansys.com/version/stable/examples/01-Modeling-Setup/HFSS_CoordinateSystem.html#general-coordinate-system-creation 

Another option is to add to this existing example instead of creating a new one. Of course you decide based on work you've already got

**Comment by gmalinve** [comment]
@DaveTwyman yes this is the example I re-used, please take a look at the linked PR #3991 .
