### ISSUE TITLE
Cannot run Icepak toolkits after installing PyAEDT (EDT 24R2)

### ISSUE THREAD

**Issue by kruglovIFX** [ansys/pyaedt#5022]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Running any Icepak toolkit after installing pyaedt leads to an error pointing to the `import <ToolKit_name>`  line of the corresponding python script

![image](https://github.com/user-attachments/assets/cf8526a0-010e-46fa-b643-f6d8cc743b9a)
![image](https://github.com/user-attachments/assets/b5bb011d-5bf2-4b92-b721-c8995e2bb32c)
![image](https://github.com/user-attachments/assets/a9efb5b9-7a4b-4c31-8816-6b188cdb7447)

### Steps To Reproduce

1. Install PyAEDT via "[PyAEDT Installer Python file]" as described in [Installation Instructions](https://aedt.docs.pyansys.com/version/stable/Getting_started/Installation.html)
2. Try any of the Icepak toolkits

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

-

**Comment by Samuelopez-ansys** [comment]
Hi @kruglovIFX ,

I am not sure what you are trying to do. In your screenshot I see an Ironpython code, but this is PyAEDT GitHub issues, so it is not a PyAEDT issue.

Just for testing, I tried locally, and it worked for me:

![image](https://github.com/user-attachments/assets/001aa3f0-bac5-4ac3-addc-8b85bd3dd523)


Please submit a support case in the Ansys customer portal, this has to be related to the installation or any other IT issue, but again this should not be related to PyAEDT if you followed the installation guidelines as you mentioned. 

Did you install PyAEDT on syslib instead of PersonalLib?

**Comment by kruglovIFX** [comment]
Hi @Samuelopez-ansys , thanks for your quick reply!

I've installed PyAEDT from the installer I downloaded from the website, it didn't ask me where to install it
![image](https://github.com/user-attachments/assets/0731c45d-221a-4833-a8a1-ef2a4a6074cb)
I see that it was installed in `C:\Users\<user>\AppData\Roaming\.pyaedt_env`

The reason I am submitting it here because we see the issue with toolkits after installing PyAEDT this way. What we are trying to do - making use of Icepak Toolkits in EDT after installing pyaedt.

**Comment by Samuelopez-ansys** [comment]
@kruglovIFX Indeed, but PyAEDT should not interact with AEDT, if you delete this folder (.pyaedt_env) does it work?

Later also try to delete your PersonalLib from the "Toolkits" folder. These are the only 2 places where the installer is interacting with your system. 

I think you should submit a support case, because this is a product issue.

**Comment by lorenzovecchietti** [comment]
Hi @kruglovIFX,

last time I saw this behavior, it was due to Powershell 7 installed on the machine. Please try to uninstall it. 

If the problem persist, as @Samuelopez-ansys suggested, please open a support case in the customer portal.

**Comment by kruglovIFX** [comment]
Hi @lorenzovecchietti ,

Unfortunately we cannot uninstall powershell on our working statins as we need it for certain things. Any workaround possible?

Thanks!

**Comment by lorenzovecchietti** [comment]
If I were you, I would adjust the order of the environment variables so that the PATH for PowerShell 7 has a lower priority. But I've not tested this.

Since this issue relates to the core product, I recommend opening a ticket on the customer portal. This way, someone from the support team can assist you more effectively in finding and testing a suitable workaround.

Thank you!
