### ISSUE TITLE
Install PyAedt with error

### ISSUE THREAD

**Issue by anspraksaph** [ansys/pyaedt#5379]
### Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### Description of the bug

Install PaAedt with error
 
![Image](https://github.com/user-attachments/assets/75338e5d-d454-43a4-bcf8-55482f4e6ddc)

### Steps To Reproduce

Clone PyAedt any place example C:\pyaedt
Open command line and type these command:
- py -3.11 -m venv venv311
- call venv311\Scripts\activate 
- python -m pip install pip -U
- python -m pip install wheel setuptools -U
- python -m pip install C:\pyaedt\.[tests]   <-------------------- get error after this 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.11

### Installed packages

Nothin come up
![Image](https://github.com/user-attachments/assets/9e99ea01-63d8-416b-8233-320a6e17ad8d)

**Comment by SMoraisAnsys** [comment]
Hi @anspraksaph. I was not aware that you could provide a target like C:\pyaedt.[tests] to pip install !
I tried what you just described on my laptop and it worked in my case.

Below is the code I used. Note that I am:
- using a Python that was installed with `hatch` (I don't know where your `py -3.11` comes from);
- cloning pyaedt in my user space and not in `C:`

```shell
C:\Users\smorais\AppData\Local\hatch\pythons\3.11\python\python.exe -m venv venv311
 .\venv311\Scripts\activate
python -m pip install pip -U
python -m pip install wheel setuptools -U
python -m pip install C:\Users\smorais\pyaedt.[tests]
```

![Image](https://github.com/user-attachments/assets/8211bd5d-7729-456f-b3c4-56b0844e80c9)

On top of being able to install it myself, we do have CI jobs that consist in testing the installation of pyaedt with the combination of:
- Python version: '3.8', '3.9', '3.10', '3.11', '3.12';
- OS: Ubuntu, Windows;
- Install target: 'all', 'installer'.
Therefore, I feel like the problem is associated to your environment. Could you try to clone the repo in another place and move inside the cloned repo (with `cd path/to/pyaedt`) to call `python -m pip install .[tests]` ?
