### ISSUE TITLE
Easy way to get capacitance matrix from Maxwell3D

### ISSUE THREAD

**Issue by Wangwei-Lan** [ansys/pyaedt#5450]
I used pyaedt to create objects, assign mesh, assign excitations and run analysis. However, I didn't find an easy way to create a report of capacitance matrix from the pyaedt. I have to create manually from the ANSYS Desktop. 

Is there an way that I can obtain the capacitance matrix using pyaedt scripts? Thanks very much. 

Best 
Wangwei

**Comment by gmalinve** [comment]
Hi @Wangwei-Lan ,

Thanks for opening this issue.
What you are asking is definitely possible.
You can get the available report quantities first, by specifying in the _context_ argument the name of your matrix (in my case _Matrix1_):
`quantities = m3d.post.available_report_quantities(display_type="Data Table", quantities_category="C", context="Matrix1")`
then these quantities will be the expressions needed to the _create_report_ method:
`report = m3d.post.create_report(expressions=quantities, plot_type="Data Table", context="Matrix1", primary_sweep_variable="X", variations={"X": "All"})`

Hope this help,

Kind regards,

Giulia 

* I link a PR to this issue because I had to fix the matrices handling in reports for Electrostatic solvers.
